// Types for get Data

export const GET_DATA = "GET_DATA";
export const GET_DATA_ATTEMPT = "GET_DATA_ATTEMPT";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";

// ############____________################

// Types for geting Single Data

export const GET_SINGLE_DATA = "GET_SINGLE_DATA";
export const GET_SINGLE_DATA_ATTEMPT = "GET_SINGLE_DATA_ATTEMPT";
export const GET_SINGLE_DATA_SUCCESS = "GET_SINGLE_DATA_SUCCESS";
export const GET_SINGLE_DATA_FAIL = "GET_SINGLE_DATA_FAIL";

// ############____________################

// Types for submit Data

export const SUBMIT_DATA = "SUBMIT_DATA";
export const SUBMIT_DATA_ATTEMPT = "SUBMIT_DATA_ATTEMPT";
export const SUBMIT_DATA_SUCCESS = "SUBMIT_DATA_SUCCESS";
export const SUBMIT_DATA_FAIL = "SUBMIT_DATA_FAIL";

// ###############_________________##############

// Types for the textFields onChange

export const CHANGE_NAME = "CHANGE_NAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const RESET_STATE_FORM = "RESET_STATE_FORM";

// ############_______________############

// Types for the Login Data

export const LOGIN_DATA = "LOGIN_DATA";
export const LOGIN_DATA_ATTEMPT = "LOGIN_DATA_ATTEMPT";
export const LOGIN_DATA_SUCCESS = "LOGIN_DATA_SUCCESS";
export const LOGIN_DATA_FAIL = "SUBMIT_DATA_FAIL";
export const SIGN_OUT_DATA = "SIGN_OUT_DATA";

// ##############___________________#############

// Types for Login onChange textFields

export const CHANGE_LOGIN_NAME = "CHANGE_LOGIN_NAME";
export const CHANGE_LOGIN_PASSWORD = "CHANGE_LOGIN_PASSWORD";
export const RESET_LOGIN_STATE = "RESET_LOGIN_STATE";

// ##############___________________#############

// Types for Student Personal Information

export const CHANGE_STUDENT_NAME = "CHANGE_STUDENT_NAME";
export const CHANGE_STUDENT_EMAIL = "CHANGE_STUDENT_EMAIL";
export const CHANGE_STUDENT_PHONE = "CHANGE_STUDENT_PHONE";
export const CHANGE_STUDENT_PROFESSIONAL_TITLE =
	"CHANGE_STUDENT_PROFESSIONAL_TITLE";
export const CHANGE_STUDENT_SUMMARY = "CHANGE_STUDENT_SUMMARY";
export const BTN_CANCEL_PERSONAL_INFORMATION =
	"BTN_CANCEL_PERSONAL_INFORMATION";

// ##############___________________#############

// Types for Student Work Experience

export const CHANGE_STUDENT_COMPANY_NAME = "CHANGE_STUDENT_COMPANY_NAME";
export const CHANGE_STUDENT_STARTING_DATE = "CHANGE_STUDENT_STARTING_DATE";
export const CHANGE_STUDENT_ENDING_DATE = "CHANGE_STUDENT_ENDING_DATE";
export const CHANGE_STUDENT_PLACE = "CHANGE_STUDENT_PLACE";
export const CHANGE_STUDENT_DESCRIPTION = "CHANGE_STUDENT_DESCRIPTION";
export const BTN_CANCEL_WORK_EXPERIENCE = "BTN_CANCEL_WORK_EXPERIENCE";
export const BTN_ADD_WORK_EXPERIENCE = "BTN_ADD_WORK_EXPERIENCE";

// ##############___________________#############

// Types for Student Technical Expertise

// Front End

export const CHANGE_STUDENT_FRONT_END_NAME = "CHANGE_STUDENT_FRONT_END_NAME";
export const CHANGE_STUDENT_FRONT_END_DESCRIPTION =
	"CHANGE_STUDENT_FRONT_END_DESCRIPTION";
export const CHANGE_STUDENT_FRONT_END_DURATION =
	"CHANGE_STUDENT_FRONT_END_DURATION";
export const BTN_ADD_FRONT_END = "BTN_ADD_FRONT_END";
export const BTN_CANCEL_FRONT_END = "BTN_CANCEL_FRONT_END";

// back End

export const CHANGE_STUDENT_BACK_END_NAME = "CHANGE_STUDENT_BACK_END_NAME";
export const CHANGE_STUDENT_BACK_END_DESCRIPTION =
	"CHANGE_STUDENT_BACK_END_DESCRIPTION";
export const CHANGE_STUDENT_BACK_END_DURATION =
	"CHANGE_STUDENT_BACK_END_DURATION";
export const BTN_ADD_BACK_END = "BTN_ADD_BACK_END";
export const BTN_CANCEL_BACK_END = "BTN_CANCEL_BACK_END";

// development Tools

export const CHANGE_STUDENT_DEVELOPMENT_TOOL_NAME =
	"CHANGE_STUDENT_DEVELOPMENT_TOOL_NAME";
export const CHANGE_STUDENT_DEVELOPMENT_TOOL_DESCRIPTION =
	"CHANGE_STUDENT_DEVELOPMENT_TOOL_DESCRIPTION";
export const CHANGE_STUDENT_DEVELOPMENT_TOOL_DURATION =
	"CHANGE_STUDENT_DEVELOPMENT_TOOL_DURATION";

// Buttons

export const BTN_ADD_DEVELOPMENT_TOOL = "BTN_ADD_DEVELOPMENT_TOOL";
export const BTN_CANCEL_DEVELOPMENT_TOOL = "BTN_CANCEL_DEVELOPMENT_TOOL";

// ##############___________________#############

// Types for Student Education

export const CHANGE_STUDENT_DEGREE_NAME='CHANGE_STUDENT_DEGREE_NAME';
export const CHANGE_STUDENT_DEGREE_LEVEL='CHANGE_STUDENT_DEGREE_LEVEL';
export const CHANGE_STUDENT_INSTITUTE_NAME='CHANGE_STUDENT_INSTITUTE_NAME';
export const CHANGE_STUDENT_MAJOR_SUBJECT='CHANGE_STUDENT_MAJOR_SUBJECT';
export const CHANGE_STUDENT_EDUCATION_PLACE='CHANGE_STUDENT_EDUCATION_PLACE';
export const CHANGE_STUDENT_PASSING_YEAR='CHANGE_STUDENT_PASSING_YEAR';

export const BTN_ADD_EDUCATION = "BTN_ADD_EDUCATION";
export const BTN_CANCEL_EDUCATION = "BTN_CANCEL_EDUCATION";

// ##############___________________#############
